# Use an OpenJDK base image
FROM openjdk:17-alpine

# Set the working directory inside the container
WORKDIR /Weddify

# Copy the Spring Boot application JAR file into the container
COPY emailapi.jar .

# Specify the command to run the application when the container starts
# CMD ["java", "-jar", "emailapi.jar"]
