# Generated by Django 3.2.14 on 2023-04-10 13:32

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('service_type', models.CharField(choices=[('Photographer', 'Photographer'), ('Venue', 'Venue'), ('Caterer', 'Caterer'), ('Bridal Services', 'Bridal Services')], max_length=100)),
                ('vendor_id', models.IntegerField()),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(choices=[('Delhi', 'Delhi'), ('Maharastra', 'Maharastra'), ('Karnataka', 'Karnataka'), ('Telangana', 'Telangana'), ('West Bengal', 'West Bengal'), ('Haryana', 'Haryana'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Rajasthan', 'Rajasthan')], max_length=100)),
                ('featured_package_price', models.IntegerField()),
                ('service_photo', models.FileField(upload_to='photos/%y/%m/%d/')),
                ('service_photo_1', models.FileField(blank=True, upload_to='photos/%y/%m/%d/')),
                ('service_photo_2', models.FileField(blank=True, upload_to='photos/%y/%m/%d/')),
                ('service_photo_3', models.FileField(blank=True, upload_to='photos/%y/%m/%d/')),
                ('service_photo_4', models.FileField(blank=True, upload_to='photos/%y/%m/%d/')),
                ('description', ckeditor.fields.RichTextField()),
                ('other_details', ckeditor.fields.RichTextField()),
                ('is_featured', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
